version: '2'
services:
    small-app:
        image: small
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://small-mysql:3306/small?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://small-elasticsearch:9200
        ports:
            - 8080:8080
    small-mysql:
        extends:
            file: mysql.yml
            service: small-mysql
    small-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: small-elasticsearch
